name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            python3 \
            python3-pip \
            libssl-dev \
            libffi-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            zlib1g-dev

          sudo apt-get install aidl  # Install AIDL
          python3 -m pip install --upgrade pip wheel setuptools
          pip install buildozer
          pip install cython
     
      - name: Clean Buildozer Cache
        run: |
          buildozer android clean

      - name: Reinstall Buildozer Dependencies
        run: |
          buildozer android debug deploy run

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: ./bin/
