name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /opt/android/sdk
      ANDROID_NDK_HOME: /opt/android/ndk

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python 3.8
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt upgrade
          sudo apt install -y python3.8 python3.8-dev

      - name: Install dependencies
        run: |
          pip install buildozer
          pip install cython==0.29.19
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            python3-pip \
            python3-dev \
            ffmpeg \
            libssl-dev \
            libffi-dev \
            libsdl2-dev \
            libltdl-dev \
            libportmidi-dev \
            libavcodec-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            zlib1g-dev

          sudo apt install libunwind-dev
          sudo apt install libgstreamer1.0-dev
          
          sudo apt-get install -y \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-libav \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev

          sudo apt-get install -y \
            build-essential \ 
            libsqlite3-dev \
            sqlite3 bzip2 \
            libbz2-dev \
            zlib1g-dev \
            libssl-dev \
            openssl \
            libgdbm-dev \ 
            libgdbm-compat-dev \ 
            liblzma-dev \
            libreadline-dev \ 
            libncursesw5-dev \
            libffi-dev \
            uuid-dev \
            libffi6
            
          python3 -m pip install --upgrade pip wheel setuptools
          sudo apt-get install aidl  # Install AIDL
          sudo apt-get install autoconf
          sudo apt install automake
          sudo apt-get libffi-dev
          sudo apt-get install libtool
  
     
      - name: Clean Buildozer Cache
        run: |
          buildozer android clean

      - name: Create buildozer.spec
        run: |
          echo "[app]" > buildozer.spec
          echo "package.name = myapp" >> buildozer.spec
          echo "package.domain = com.example.myapp" >> buildozer.spec
          echo "source.include_exts = py,png,jpg,kv,atlas" >> buildozer.spec
          echo "version = 1.0" >> buildozer.spec
          echo "requirements = kivy" >> buildozer.spec
          echo "" >> buildozer.spec
          echo "[buildozer]" >> buildozer.spec
          echo "log_level = 2" >> buildozer.spec
          echo "warn_on_root = 1" >> buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: ./bin/
